apiVersion: v1
kind: Service
metadata:
  name: signaling-server
  namespace: tandem-watch
  labels:
    app: signaling-server
spec:
  type: NodePort
  selector:
    app: signaling-server
  ports:
  - name: ws
    port: 4001
    targetPort: 4001
    nodePort: 30401          # Valid NodePort range: 30000-32767
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
