apiVersion: v1
kind: Service
metadata:
  name: signaling-server
  namespace: tandem-watch
  labels:
    app: signaling-server
spec:
  type: LoadBalancer
  selector:
    app: signaling-server
  ports:
  - name: ws
    port: 80
    targetPort: 4001
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
